version: '3.8'

services:
  db:
    image: postgres:15.3
    container_name: postgres-with-cron
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: model_store
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d # Папка с init-скриптами
    command: >
      bash -c "
      apt-get update && apt-get install -y postgresql-15-cron && \
      echo \"shared_preload_libraries = 'pg_cron'\" >> /usr/share/postgresql/postgresql.conf.sample && \
      echo \"cron.database_name = 'model_store'\" >> /usr/share/postgresql/postgresql.conf.sample && \
      docker-entrypoint.sh postgres
      "
  minio:
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: 'minio_user'
      MINIO_ROOT_PASSWORD: 'minio_password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data
  backend:
    image: ready555/model_store:v1.8
    depends_on:
      - db
      - minio
    ports:
      - "8081:8081"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/model_store
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root

      SPRING_MAIL_HOST: smtp.mail.ru
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: yourMail
      SPRING_MAIL_PASSWORD: yourPass

      S3_ACCESS-KEY: minio_user
      S3_SECRET-KEY: minio_password
      S3_ENDPOINT: http://minio:9000  # Перекроет значение из application.yml
      S3_REGION: us-east-1
      S3_PARTICIPANT_BUCKET_NAME: participant-bucket # Папка фотографий пользователей
      S3_PRODUCT_BUCKET_NAME: product-bucket # Папка фотографий продуктов
      S3_SYSTEM_BUCKET_NAME: system-bucket  # Папка системный фото
      S3_ORDER_BUCKET_NAME: order-bucket   # Папка доказательств (оплаты, споров) пользователей

      APP_MAX_PARTICIPANT_IMAGES: 1
      APP_MAX_PRODUCT_IMAGES: 4
      APP_PRIVATE_KEY_PATH: /backend/keys/private.pk8
      APP_PUBLIC_KEY_PATH: /backend/keys/public.key
      APP_EMAIL_FROM: yourMail
networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  minio_data:
    driver: local