package com.model_store.exception.constant;

public enum ErrorCode {
    IMAGE_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    PARTICIPANT_NOT_FOUND,
    PRODUCT_ALREADY_IN_BASKET,
    TOKEN_INVALID_OR_EXPIRED,

    PRODUCT_ALREADY_EXISTS,
    INVALID_ADDRESS,
    INVALID_TRANSFER,
    OWN_PRODUCT_ORDER_FORBIDDEN,
    OUT_OF_STOCK,
    WAITING_VERIFY,
    ACCOUNT_BLOCKED,
    ACCOUNT_DELETED,
    VERIFICATION_COOLDOWN,
    VERIFICATION_DAILY_LIMIT,
    INTERNAL_ERROR
}
