version: '3.5'

services:
  db_model_store:
    container_name: db_model_store
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    image: postgres:16.2-alpine