version: '3.8'

networks:
  3d-network:
    external: true

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:15.3
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: model_store
      TZ: Europe/Moscow
    ports:
      - "5432:5432"
    networks:
      - 3d-network

  pgadmin:
    image: dpage/pgadmin4:latest
    deploy:
      replicas: 1
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.ru"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    networks:
      - 3d-network