version: '3.8'

networks:
  3d-network:
    external: true

volumes:
  minio_data:
    driver: local

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    volumes:
    - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_SERVER_URL: http://minio:9000
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: ItLS122jSf2x
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data
    networks:
      - 3d-network
